In [115]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import StandardScaler


In [116]:
def CustomLog(X):
    return np.log(X)


def PreprocData(X, Y):

    pipe = make_pipeline(
        FunctionTransformer(CustomLog),StandardScaler()
    )
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y)
    pipe.fit(X_train, Y_train)
    return pipe.transform(X_test), Y_test

iris = load_iris()
X, Y = iris.data, iris.target

In [117]:
print(X)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [118]:
X_transformed, Y_transformed = PreprocData(X, Y)
print(X_transformed)

[[-1.10836265  0.19593746 -1.25218547 -2.12788678]
 [ 0.04207487 -0.50470812  0.80120913  1.10320526]
 [-0.19733754 -0.75505352  0.4754313   0.47986875]
 [ 1.51726864  1.22527501  1.10163735  1.14470853]
 [ 0.04207487 -0.75505352  0.80120913  0.86569163]
 [ 0.15870256 -0.02977915  0.80120913  0.81072209]
 [-0.44545775  1.77626818 -1.042172   -0.71845669]
 [ 0.38614208 -0.02977915  0.62807446  0.5552135 ]
 [ 0.71368756  0.19593746  0.9279046   0.81072209]
 [ 1.22690339  0.19593746  0.80120913  1.05993537]
 [ 0.60624354 -0.75505352  0.73408347  0.81072209]
 [-0.70294317  2.1205269  -1.25218547 -2.12788678]
 [ 1.70419962 -0.50470812  1.10163735  0.86569163]
 [ 1.02622558  0.19593746  0.55348806  0.5552135 ]
 [-0.97052859  1.03135402 -1.49229692 -1.01093986]
 [ 1.22690339  0.41448724  0.98783661  1.05993537]
 [-0.07658123 -0.50470812  0.59119566  0.47986875]
 [ 0.8194657  -0.50470812  0.62807446  0.62535779]
 [ 0.60624354  0.62631133  1.07390254  1.14470853]
 [ 1.32507132  0.41448724  0.66